
services:
  db: # this is the configuration for the database service
    container_name: postgres
    image: postgres:16 # changed from "latest" to avoid any future issues when a newer version is released that may bring up compatibility issues 
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - backend_network
    restart: unless-stopped
    healthcheck: # this gives confirmation that the database
    #           is ready before python tries to connect to it
      test: ["CMD-SHELL", "pg_isready -U postgres -d IEC2029_Database"]
      interval: 10s
      timeout: 5s
      retries: 5

  python:  # this is the configuration for the python service
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python
  
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "8888:8888"   # for Jupyter 
    networks:
      - backend_network
    restart: unless-stopped
    volumes:
      - ./scripts:/app/scripts    
      - ./data:/app/data

networks:
  backend_network:
    driver: bridge # this allows python and postgres to talk to each other

volumes:
  db: # this keeps data from disappearing when the container stops