version: "3.9"

services:
  db:
    container_name: postgres
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bank
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bank"]
      interval: 10s
      timeout: 5s
      retries: 5

  python:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: bank
      DB_USER: postgres
      DB_PASSWORD: password
    ports:
      - "8888:8888"   # for Jupyter 
    networks:
      - backend

networks:
  backend:
    driver: bridge # this allows python and postgres to talk to each other

volumes:
  db: # this keeps data from disappearing when the container stops